In [1]:
import pandas as pd

In [8]:
# ▶ 1. 파일 불러오기
df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/FinalProject/data/피처선택완료_데이터/combined_data_1.csv')
df2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/FinalProject/data/피처선택완료_데이터/combined_data_2.csv')

# ▶ 2. 데이터 결합
merged_df = pd.merge(df1, df2.drop(columns=['Segment'], errors='ignore'), on=['ID', '기준년월'], how='inner')
# merged_df = merged_df[merged_df['기준년월'] == 201812] # 12월 데이터만 할 경우!
merged_df = merged_df.drop(columns=['기준년월'])
merged_df

# ▶ 3. CSV로 저장
merged_df.to_csv('/content/drive/MyDrive/Colab Notebooks/FinalProject/data/최종데이터/청구잔액_최종데이터.csv', index=False, encoding='utf-8-sig')

/tmp/ipython-input-8-2552529470.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/FinalProject/data/피처선택완료_데이터/combined_data_1.csv')
/tmp/ipython-input-8-2552529470.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/FinalProject/data/피처선택완료_데이터/combined_data_2.csv')

In [9]:
merged_df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/FinalProject/data/최종데이터/청구잔액_최종데이터.csv') # 7-12월 데이터
display(merged_df1)

/tmp/ipython-input-9-2199638015.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/FinalProject/data/최종데이터/청구잔액_최종데이터.csv') # 7-12월 데이터

,ID,Segment,월중평잔_일시불_B0M,평잔_6M,평잔_CA_6M,잔액_리볼빙일시불이월_B0M,RV_최대잔액_R3M,평잔_일시불_해외_6M,월중평잔_일시불,RV_평균잔액_R3M,...,상환개월수_결제일_R6M,포인트_이용포인트_R3M,상환개월수_결제일_R3M,연체건수_R3M,마일_적립포인트_R12M,혜택수혜금액_R3M,선결제건수_R3M,할인금액_R3M,마일_잔여포인트_B0M,포인트_포인트_월적립_R3M
0,TRAIN_000000,D,1084,15988,17008,0,0,0,1503,0,...,5,1296,3,0,0,3,0,0,0,0
1,TRAIN_000001,E,4090,7045,0,0,0,0,4447,0,...,6,0,3,0,0,0,0,0,0,0
2,TRAIN_000002,C,5006,66549,43351,6795,5134,0,5540,2848,...,6,2765,3,0,0,121,0,0,0,0
3,TRAIN_000003,D,487,30139,30697,0,0,0,606,0,...,5,2467,3,0,0,3,0,0,0,0
4,TRAIN_000004,E,0,28,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,TEST_99995,NaN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2999996,TEST_99996,NaN,260,275,0,0,0,0,256,0,...,5,0,3,0,0,149,2,150,0,0
2999997,TEST_99997,NaN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2999998,TEST_99998,NaN,16911,20549,0,0,0,240,14005,0,...,1,3804,1,0,0,0,3,0,0,0
2999999,TEST_99999,NaN,37,18,0,0,0,0,10,0,...,6,0,3,0,0,0,0,0,0,0